apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hawtio-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hawtio-app
    spec:
      containers:
      - name: hawtio-app
        image: testregistrocontenedores.azurecr.io/hawtio-app:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 500m
            memory: 1000Mi 
          limits:
            cpu: 600m
            memory: 1300Mi            
      imagePullSecrets:
      - name: registrosatrack
      
---
apiVersion: v1
kind: Service
metadata:
  name: hawtio-app
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: hawtio-app
